"""empty message

迁移 ID: 68463f3e5f33
父迁移: da5a91612ef2
创建时间: 2024-04-09 14:24:27.354048

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '68463f3e5f33'
down_revision: str | Sequence[str] | None = 'da5a91612ef2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_fishing_fishingrecord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coin', sa.Integer(), nullable=False))
        batch_op.alter_column('fishes',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_fishing_fishingrecord', schema=None) as batch_op:
        batch_op.alter_column('fishes',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('coin')

    # ### end Alembic commands ###
