"""add special_fishes field

迁移 ID: e9015df43907
父迁移: f70bdeaec7a4
创建时间: 2024-04-20 12:43:35.168261

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e9015df43907'
down_revision: str | Sequence[str] | None = 'f70bdeaec7a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_fishing_fishingrecord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_fishes', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_fishing_fishingrecord', schema=None) as batch_op:
        batch_op.drop_column('special_fishes')

    # ### end Alembic commands ###
